#!/bin/sh

LOCAL_IP=`ifconfig | grep -A 1 'en0'  | tail -1 | cut -d ' ' -f 2`
export CASSANDRA_HOST="$LOCAL_IP:8091"
export CASSANDRA_HOST_URL=$CASSANDRA_HOST
echo $CASSANDRA_HOST
echo $CASSANDRA_HOST_URL
