##################################################################################################
# Cart service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
    service: cartservice
spec:
  ports:
    - port: 7070
      name: http
  selector:
    app: cartservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-app
  labels:
    account: cartservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cartservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
      version: v1
  template:
    metadata:
      labels:
        app: cartservice
        version: v1
    spec:
      serviceAccountName: cart-app
      containers:
        - name: cartservice
          image: docker.io/testdockerramesh/cart-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cart-service-vs
spec:
  hosts:
  - "*"
  gateways:
  - cart-gateway
  http:
  - match:
    - uri:
        prefix: /cartservice
    - uri:
        exact: /cartservice/swagger-ui.html
    route:
    - destination:
        host: cartservice
        port:
          number: 7070
